Different models are compared with to test the activity of different small molecules on the HIV virus.

The feature vectors contains the numbers of functional groups in the small molecules and the labels are done as 2 or -1 depending if they are active or inactive. A total of 146 features is taken for each small molecule.

In [10]:
# Importing different libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

# sklearn library
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier

In [11]:
# Matrix reading from the files
def read_file(txt_file, mat_a):
    file = open(txt_file, "r")
    for line in file:
        ns = line.split()
        no = [float(n) for n in ns]
        mat_a.append(no)
    file.close()
X = []
Y = []
read_file("hiv_inhibitors.txt", X)
read_file("hiv_activity.txt", Y)
#print(X)
#print(Y)


In [12]:
# Creating training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
#print(Y_test)

# Standardizing the data
ss=StandardScaler()
X_train_st=ss.fit_transform(X_train)
X_test_st=ss.fit_transform(X_test)

In [13]:
#Decision Tree Clasifier

# Training Decision tree model
DTClassifier=DecisionTreeClassifier(criterion='entropy', random_state=42)
DTClassifier.fit(X_train,Y_train)

# Testing
Y_pred = DTClassifier.predict(X_test)

# Accuracy of the model
#
print('The accuracy of decision tree is: ', metrics.accuracy_score(Y_pred,Y_test))

# Confusion Matrix
print(confusion_matrix(Y_pred, Y_test))

# Different f1 scores
print('F1 Score with macro average: ',f1_score(Y_test, Y_pred, average='macro'))
print('F1 Score with micro average: ',f1_score(Y_test, Y_pred, average='micro'))
print('F1 Score with weighted average: ',f1_score(Y_test, Y_pred, average='weighted'))

The accuracy of decision tree is:  0.89
[[247  20]
 [ 13  20]]
F1 Score with macro average:  0.7426633048270126
F1 Score with micro average:  0.89
F1 Score with weighted average:  0.8854565776818901


In [14]:
Y_train_np = np.array(Y_train)

#Naive Bayes Classifier
# Training the model
NBClassifier=GaussianNB()
NBClassifier.fit(X_train_st, Y_train_np.ravel())

# Testing
Y_pred1 = NBClassifier.predict(X_test)

# Accuracy of the model
print('The accuracy of Naive baise is: ', metrics.accuracy_score(Y_pred1, Y_test))

# Confusion Matrix
print(confusion_matrix(Y_pred1, Y_test))

# Different f1 scores
print('F1 Score with macro average: ',f1_score(Y_test, Y_pred1, average='macro'))
print('F1 Score with micro average: ',f1_score(Y_test, Y_pred1, average='micro'))
print('F1 Score with weighted average: ',f1_score(Y_test, Y_pred1, average='weighted'))

The accuracy of Naive baise is:  0.86
[[258  40]
 [  2   0]]
F1 Score with macro average:  0.46236559139784944
F1 Score with micro average:  0.8599999999999999
F1 Score with weighted average:  0.8014336917562723


In [15]:
#Random Forest Classifier Algorithm

# Training the model
model = RandomForestClassifier(n_estimators=10, random_state=25)
model.fit(X_train, Y_train_np.ravel())

# Testing
Y_pred2 = model.predict(X_test)

# Accuracy of the model
print('The accuracy of Random Forest Classifier is: ', metrics.accuracy_score(Y_pred2,Y_test))

# Confusion Matrix
print(confusion_matrix(Y_pred2, Y_test))

# Different f1 scores
print('F1 Score with macro average: ',f1_score(Y_test, Y_pred2, average='macro'))
print('F1 Score with micro average: ',f1_score(Y_test, Y_pred2, average='micro'))
print('F1 Score with weighted average: ',f1_score(Y_test, Y_pred2, average='weighted'))

The accuracy of Random Forest Classifier is:  0.92
[[258  22]
 [  2  18]]
F1 Score with macro average:  0.7777777777777778
F1 Score with micro average:  0.92
F1 Score with weighted average:  0.9081481481481481


In [16]:
#SVM 

# Training the model
classifier_object = SVC(kernel ='linear', gamma='auto', C=2)
classifier_object = SVC(probability=True)
classifier_object.fit(X_train, Y_train_np.ravel())

# Testing 
Y_pred3 = classifier_object.predict(X_test)

# Accuracy of the model
print('The accuracy of Support Vector Classifier is: ', metrics.accuracy_score(Y_pred3,Y_test))

# Confusion Matrix
print(confusion_matrix(Y_pred3, Y_test))

# Different f1 scores
print('F1 Score with macro average: ',f1_score(Y_test, Y_pred3, average='macro'))
print('F1 Score with micro average: ',f1_score(Y_test, Y_pred3, average='micro'))
print('F1 Score with weighted average: ',f1_score(Y_test, Y_pred3, average='weighted'))

The accuracy of Support Vector Classifier is:  0.8966666666666666
[[260  31]
 [  0   9]]
F1 Score with macro average:  0.655542797881403
F1 Score with micro average:  0.8966666666666666
F1 Score with weighted average:  0.8668864278923911


In [17]:
# SGD model

#Training the model
classifier_Sgd = make_pipeline(StandardScaler(),SGDClassifier(max_iter=1000, tol=1e-3))
classifier_Sgd.fit(X_train, Y_train_np.ravel())

#Testing the model
Y_pred4 = classifier_Sgd.predict(X_test)

# Accuracy of the model
print('The accuracy of Stochastic Gradient Descent Classifier is: ', metrics.accuracy_score(Y_pred4,Y_test))

# Confusion Matrix
print(confusion_matrix(Y_pred4, Y_test))

# Different f1 scores
print('F1 Score with macro average: ',f1_score(Y_test, Y_pred4, average='macro'))
print('F1 Score with micro average: ',f1_score(Y_test, Y_pred4, average='micro'))
print('F1 Score with weighted average: ',f1_score(Y_test, Y_pred4, average='weighted'))

The accuracy of Stochastic Gradient Descent Classifier is:  0.8633333333333333
[[241  22]
 [ 19  18]]
F1 Score with macro average:  0.6945692930396563
F1 Score with micro average:  0.8633333333333333
F1 Score with weighted average:  0.8610629650782615
